for i in range (1):
    print(i, end=' ')

# *********************
# A step-by-step explanation of the code: 

# for i in range(1):

#     print(i, end=' ')

# We have a for loop that iterates over the values in the range created by range(1). 
# The range(1) generates a sequence of numbers from 0 up to, but not including, 1. Since it only includes one value (0), 
# the loop will run only once.

# In the loop, the variable i takes on the value of 0, which is the only value generated by range(1).

# Inside the loop, we have the print statement. 
# This statement prints the current value of i, which is 0. 
# The end parameter is set to a space (' '), which means it will print a space after the value of i.

# After printing the value of i (0) with a space character after it,
#  the loop completes its one and only iteration.

# So, the code will output: 0
