for k in range(3,9,2):
    print(k , end =' ')

# ***********************************************************
# Solution - 

# for k in range(3, 9, 2):
#     print(k, end=' ')

# The code begins with a for loop that specifies a loop variable k. 
# It is used to iterate over a range of values.

# The range(3, 9, 2) function is used to define the range of values for k.
#  The three arguments inside range are:

# Start: 3
# Stop: 9 (the loop will stop before reaching 9)
# Step: 2 (the increment between each value)
# The loop is designed to iterate through the values generated by range(3, 9, 2).

# In the first iteration of the loop, k takes the value 3. 
# It then proceeds to the next iteration.

# In the second iteration, k takes the value 5. 
# It continues to the next iteration.

# In the third and final iteration, k takes the value 7. 
# The loop has reached the end of the specified range.

# Inside the loop, the print statement is used to display 
# the current value of k. The end=' ' argument is specified to 
# ensure that a space character is added after each value.

# After printing each value of k, the loop continues to the next iteration.

# Once the loop has finished all iterations, the program completes, 
# and the output is displayed.

# The output of this code is: 3 5 7

# It shows the values of k (3, 5, and 7) separated by space characters as 
# specified in the print statement.